// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'D:/code/tao-api/tao-api-frontend-master/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import StarOutlined from 'D:/code/tao-api/tao-api-frontend-master/node_modules/@ant-design/icons/es/icons/StarOutlined';
import SmileOutlined from 'D:/code/tao-api/tao-api-frontend-master/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'D:/code/tao-api/tao-api-frontend-master/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'D:/code/tao-api/tao-api-frontend-master/node_modules/@ant-design/icons/es/icons/TableOutlined';
import UserOutlined from 'D:/code/tao-api/tao-api-frontend-master/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { HomeOutlined, StarOutlined, SmileOutlined, CrownOutlined, TableOutlined, UserOutlined };
